### ISSUE TITLE
Destination displays always show the last  station on the schedule

### ISSUE THREAD

**Issue by tomco111** [MisterJulsen/Create-Train-Navigator#92]
**Version:**
 - MC 1.19.2
 - Forge 43.3.13
 - Mod Version 0.8.0
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior
Prepare a route with even stations
2. Prepare a train with destination displays
3. Initialize the train

**Expected behavior**
The displays will show the last station you put on the schedules

**Additional context**
This is a version-locked error from 0.6.0 and above, as I have not seen the error w/ the earlier versions.

**Comment by MisterJulsen** [comment]
According to your message, you are using version 0.8.0 of CRN. Please try the latest version of this mod as many of these bugs have been fixed in newer versions.

**Comment by michelpreuss** [comment]
The problem is not fixed. On destination displays on trains there is still the wrong destination displayed
